export const cats = {
  mainCats: [
    'shop-all',
    'mens-clothing',
    'womens-clothing',
    'juniors-clothing',
    'equipment',
    'sale',
  ],
  subCats: [
    'tops',
    'bottoms',
    'outerwear',
    'shoes',
    'sale',
    'accessories',
    'clubs',
    'balls',
    'misc',
  ],
  apparel: ['tops', 'bottoms', 'outerwear', 'shoes', 'sale', 'accessories'],
  equipment: ['clubs', 'balls', 'misc', 'sale'],
  all: [
    'shop-all',
    'mens-clothing',
    'womens-clothing',
    'juniors-clothing',
    'equipment',
    'sale',
    'tops',
    'bottoms',
    'outerwear',
    'shoes',
    'accessories',
    'clubs',
    'balls',
    'misc',
  ],
};

export const catTypes = {
  'shop-all': 'all',
  'mens-clothing': 'apparel',
  'womens-clothing': 'apparel',
  'juniors-clothing': 'apparel',
  equipment: 'equipment',
  sale: 'all',
};
